plugins {
	id 'java'
	id 'io.spring.dependency-management' version '1.1.4' apply false
}

group = 'com.dotran.oms'

allprojects {
	group = project.property('group')

	repositories {
		mavenCentral()
	}
}

subprojects {
	apply plugin: 'java-library'
	apply plugin: 'io.spring.dependency-management'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:3.2.3"
		}
	}

	dependencies {

		// Lombok
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'

		testCompileOnly 'org.projectlombok:lombok'
		testAnnotationProcessor 'org.projectlombok:lombok'

		// Logging
		compileOnly 'org.slf4j:slf4j-api'
	}

	test {
		useJUnitPlatform()
	}
}

// oms-core is only an aggregator
tasks.named('jar') {
	enabled = false
}