plugins {
    id 'java'
}

group = 'com.dotran.oms'
version = project.findProperty("version")

repositories {
    mavenCentral()
}

dependencies {
    api project(':core-common')

    // Spring
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Apache
    api 'org.apache.poi:poi-ooxml:5.4.1'
}

test {
    useJUnitPlatform()
}