plugins {
    id 'java'
}

group = 'com.dotran.oms'
version = project.findProperty("version")

repositories {
    mavenCentral()
}

dependencies {
    api project(':core-common')

    // Spring
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // AWS
    api platform("software.amazon.awssdk:bom:2.31.76")
    api 'software.amazon.awssdk:s3'
    api "software.amazon.awssdk:dynamodb"
    api "software.amazon.awssdk:dynamodb-enhanced"
}

test {
    useJUnitPlatform()
}