plugins {
    id 'java'
}

group = 'com.dotran.oms'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    api project(':core-common')

    // Spring
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // AWS
    implementation platform("software.amazon.awssdk:bom:2.31.76")
    implementation 'software.amazon.awssdk:s3'
    implementation "software.amazon.awssdk:dynamodb"
    implementation "software.amazon.awssdk:dynamodb-enhanced"
}

test {
    useJUnitPlatform()
}