plugins {
    id 'java'
}

group = 'com.dotran.oms'
version = project.findProperty("version")

repositories {
    mavenCentral()
}

dependencies {
    api project(':core-common')

    // Spring
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework:spring-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Swagger
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0") {
        exclude group: "org.apache.commons", module: "commons-lang3"
    }

    api 'jakarta.servlet:jakarta.servlet-api'
}

test {
    useJUnitPlatform()
}